DROP SCHEMA IF EXISTS task3 CASCADE;
CREATE SCHEMA task3;

SHOW search_path ;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

DROP TABLE IF EXISTS task3.Teacher CASCADE;
DROP TABLE IF EXISTS task3.Lesson CASCADE;
DROP TABLE IF EXISTS task3.Student CASCADE;
DROP TABLE IF EXISTS task3.LessonToStudent CASCADE;

-- Создание таблицы Department
CREATE TABLE task3.Teacher
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

-- Создание таблицы Employee
CREATE TABLE task3.Lesson
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50),
    teacher_id INT,
    FOREIGN KEY (teacher_id) REFERENCES task3.Teacher (id) ON DELETE SET NULL
);

-- Создание таблицы Project
CREATE TABLE task3.Student
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE
);

-- Создание таблицы-связи EmployeeProject
CREATE TABLE task3.Lesson_Student
(
    lesson_id INT,
    student_id  INT,
    FOREIGN KEY (lesson_id) REFERENCES task3.Lesson (id) ON DELETE CASCADE ,
    FOREIGN KEY (student_id) REFERENCES task3.Student (id) ON DELETE CASCADE
);


-- Вставка данных
INSERT INTO task3.Teacher (name)
VALUES ('Alex'); -- 1
INSERT INTO task3.Teacher (name)
VALUES ('Viktor'); -- 2
INSERT INTO task3.Teacher (name)
VALUES ('Stas'); -- 3



INSERT INTO task3.Lesson (name, teacher_id)
VALUES ('Физика', 1); -- 1
INSERT INTO task3.Lesson (name, teacher_id)
VALUES ('Математика', 2); -- 2
INSERT INTO task3.Lesson (name, teacher_id)
VALUES ('Физкультура', 3); -- 3
INSERT INTO task3.Lesson (name, teacher_id)
VALUES ('Программирование', 3); -- 4



INSERT INTO task3.Student (name)
VALUES ('Федор'); -- 1
INSERT INTO task3.Student (name)
VALUES ('Маша'); -- 2
INSERT INTO task3.Student (name)
VALUES ('Леша'); -- 3
INSERT INTO task3.Student (name)
VALUES ('Вася'); -- 4

